# Generated by Django 3.2 on 2021-04-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='movimento_ordem',
            field=models.IntegerField(default=10000),
        ),
    ]
